language: cpp

compiler:
  - gcc

script:
  - make

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api_key: $GITPERM
  file:
    - "README.md"
    - "space"
  skip_cleanup: true
  on:
    tags: true

branches:
  except:
    - /^*-v[0-9]/
